In [6]:
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [7]:
engine = create_engine("postgres://postgres:faB17&rigeme@flightsdata.cxtoxxxge4vx.us-east-2.rds.amazonaws.com/flightsdata")

In [8]:
full_flight_df = pd.read_sql_query("SELECT * FROM full_flight_2019", engine)

In [9]:
full_flight_df

,origin,origin_city,day_of_month,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,dest_airport_id,...,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,cancelled,diverted,distance,dest_city
0,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N203JB,1189,10721,1072102,11278,...,DCA,2134.0,0.0,2100-2159,2354.0,1.0,0.0,0.0,399,"washington,dc"
1,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N178JB,1209,10721,1072102,12451,...,JAX,1525.0,0.0,1500-1559,1831.0,0.0,0.0,0.0,1010,"jacksonville,fl"
2,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N318JB,1215,10721,1072102,10792,...,BUF,1813.0,1.0,1300-1359,1950.0,1.0,0.0,0.0,395,"buffalo,ny"
3,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N294JB,1217,10721,1072102,12478,...,JFK,1536.0,1.0,1500-1559,1651.0,1.0,0.0,0.0,187,"newyork,ny"
4,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N216JB,1231,10721,1072102,12953,...,LGA,1948.0,1.0,1500-1559,2052.0,1.0,0.0,0.0,184,"newyork,ny"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545335,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N216JB,1109,10721,1072102,12451,...,JAX,829.0,0.0,0800-0859,1135.0,0.0,0.0,0.0,1010,"jacksonville,fl"
545336,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N775JB,1115,10721,1072102,11298,...,DFW,1444.0,0.0,1400-1459,1818.0,0.0,0.0,0.0,1562,"fortworth,tx"
545337,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N249JB,1137,10721,1072102,11433,...,DTW,738.0,0.0,0700-0759,950.0,0.0,0.0,0.0,632,"detroit,mi"
545338,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N298JB,1155,10721,1072102,11278,...,DCA,1541.0,1.0,1400-1459,1717.0,1.0,0.0,0.0,399,"washington,dc"
545339,BOS,"boston,ma",2019-01-31,20409,Jet Blue,N266JB,1159,10721,1072102,14100,...,PHL,1940.0,1.0,1800-1859,2102.0,1.0,0.0,0.0,280,"philadelphia,pa"

In [10]:
full_flight_df.to_csv("full_flight.csv", index=False)